language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g testacular@canary
  - npm install -g grunt-cli

script: "npm test"

branches:
  only:
  - master

deploy:
  provider: releases
  file: dist/angular-piwik.js
  skip_cleanup: true
  on:
    tags: true
    repo: rnanania/ang-piwik
