language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g testacular@canary
  - npm install -g grunt-cli

script: "npm test"

deploy:
  provider: releases
  user: $TRAVIS_BUILD_USER
  password: $TRAVIS_BUILD_PASS
  file: dist/angular-piwik.js
  skip_cleanup: true
  on:
    tags: true
    repo: rnanania/ang-piwik
    all_branches: true
